// HULLOR — পণ্যের তালিকা
// নতুন প্রোডাক্ট যোগ করতে চাইলে এই অ্যারেতে একটি নতুন অবজেক্ট যোগ করুন।
// image ফাইলগুলো public/images/ ফোল্ডারে রাখতে হবে। এখন সবগুলো ডেমো ছবি ব্যবহার করা হয়েছে।

const CATEGORIES = [
  { id: "all", name: "সকল পণ্য" },
  { id: "shirt", name: "শার্ট" },
  { id: "polo", name: "পোলো টি-শার্ট" },
  { id: "dropshoulder", name: "ড্রপ শোল্ডার" },
  { id: "pants", name: "প্যান্ট" },
  { id: "combo", name: "কম্বো অফার" },
  { id: "punjabi", name: "পাঞ্জাবি" },
  { id: "jersey", name: "জার্সি" },
];

const PRODUCTS = [

  {
    featured: true,
    id: "shirt-01",
    code: "FMSHDAS",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHDAS.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    id: "shirt-02",
    code: "FMSHRED",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHRED.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    id: "shirt-03",
    code: "FMSHBLU",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHBLU.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    featured: true,
    id: "shirt-04",
    code: "FMSHMRN",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHMRN.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    id: "shirt-05",
    code: "FMSHWHT",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHWHT.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    id: "shirt-06",
    code: "FMSHCYN",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHCYN.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    featured: true,
    id: "shirt-07",
    code: "FMSHASH",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHASH.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    id: "shirt-08",
    code: "FMSHPNK",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHPNK.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    id: "shirt-09",
    code: "FMSHSBL",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHSBL.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    featured: true,
    id: "shirt-10",
    code: "FMSHBLK",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHBLK.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    id: "shirt-11",
    code: "FMSHGRN",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHGRN.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },
  {
    id: "shirt-12",
    code: "FMSHORG",
    name: "Premium Men's Long Sleeve Formal Cotton Shirt",
    category: "shirt",
    fabric: "প্রিমিয়াম কটন ফেব্রিক",
    fit: "রেগুলার ফিট",
    care: "৩০°C ঠান্ডা পানিতে ধোয়া, মিডিয়াম হিটে আয়রন করুন",
    price: 650,
    oldPrice: 950,
    image: "/images/folder/formal_shirt/FMSHORG.jpg",
    sizes: ["M", "L", "XL"],
    desc: "প্রিমিয়াম কটন ফেব্রিকে তৈরি ফুল স্লিভ ফরমাল শার্ট। অফিস, মিটিং, পার্টি ও দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
  },

  // কম্বো অফার পণ্যসমূহ

{ 
  featured: true,
  id: "SHCMWH",
  code: "SHCMWH",
  name: "শার্ট গিফট কম্বো",
  category: "combo",
  fabric: "অফসেট ফেব্রিক",
  fit: "রেগুলার ফিট",
  care: "ঠান্ডা পানিতে ধুয়ে ছায়ায় শুকিয়ে নিন",
  price: 999,
  oldPrice: 1500,
  image: "/images/SHCMWH.jpg",
  sizes: ["M", "L", "XL", "XXL"],
  desc: "আপনার প্রিয় মানুষকে দেওয়ার জন্য একটি স্টাইলিশ ও স্মরণীয় গিফট কম্বো। জন্মদিন, ভালোবাসার মানুষ, বন্ধু, ভাই কিংবা যেকোনো বিশেষ উপলক্ষের জন্য উপযুক্ত। কম্বোতে রয়েছে একটি স্টাইলিশ শার্ট, একটি প্রিমিয়াম ঘড়ি, একটি মানিব্যাগ, একটি বডি স্প্রে, একটি ট্রেন্ডি সানগ্লাস, একটি ফ্যাশনেবল বেল্ট এবং একটি গিফট চিরকুট।"
},

{ 
  id: "SHCMNVB",
  code: "SHCMNVB",
  name: "শার্ট গিফট কম্বো",
  category: "combo",
  fabric: "অফসেট ফেব্রিক",
  fit: "রেগুলার ফিট",
  care: "হালকা ডিটারজেন্ট ব্যবহার করে ধুয়ে নিন",
  price: 999,
  oldPrice: 1500,
  image: "/images/SHCMNVB.jpg",
  sizes: ["M", "L", "XL", "XXL"],
  desc: "স্টাইল ও উপহারের সুন্দর সমন্বয়ে তৈরি একটি আকর্ষণীয় গিফট কম্বো। বিশেষ মানুষকে চমকে দিতে এই কম্বো হতে পারে দারুণ একটি পছন্দ। কম্বোতে রয়েছে একটি স্টাইলিশ শার্ট, একটি প্রিমিয়াম ঘড়ি, একটি মানিব্যাগ, একটি বডি স্প্রে, একটি ট্রেন্ডি সানগ্লাস, একটি ফ্যাশনেবল বেল্ট এবং একটি গিফট চিরকুট।"
},

{ 
  id: "SHCMCY",
  code: "SHCMCY",
  name: "শার্ট গিফট কম্বো",
  category: "combo",
  fabric: "অফসেট ফেব্রিক",
  fit: "রেগুলার ফিট",
  care: "ইস্ত্রি করার সময় কম তাপমাত্রা ব্যবহার করুন",
  price: 999,
  oldPrice: 1500,
  image: "/images/SHCMCY.jpg",
  sizes: ["M", "L", "XL", "XXL"],
  desc: "প্রিয়জনের জন্য রুচিশীল ও ব্যবহারযোগ্য উপহারের একটি সম্পূর্ণ প্যাকেজ। জন্মদিন, বিশেষ দিন কিংবা যেকোনো আনন্দের মুহূর্তকে আরও স্মরণীয় করে তুলতে এই গিফট কম্বোটি উপযুক্ত। কম্বোতে রয়েছে একটি স্টাইলিশ শার্ট, একটি প্রিমিয়াম ঘড়ি, একটি মানিব্যাগ, একটি বডি স্প্রে, একটি ট্রেন্ডি সানগ্লাস, একটি ফ্যাশনেবল বেল্ট এবং একটি গিফট চিরকুট।"
},

{ 
  id: "SHCMGR",
  code: "SHCMGR",
  name: "শার্ট গিফট কম্বো",
  category: "combo",
  fabric: "অফসেট ফেব্রিক",
  fit: "রেগুলার ফিট",
  care: "ধোয়ার পর কাপড়টি স্বাভাবিকভাবে শুকিয়ে নিন",
  price: 999,
  oldPrice: 1500,
  image: "/images/SHCMGR.jpg",
  sizes: ["M", "L", "XL", "XXL"],
  desc: "একসাথে প্রয়োজনীয় ও স্টাইলিশ কয়েকটি পণ্য নিয়ে তৈরি একটি সম্পূর্ণ গিফট সেট। প্রিয় মানুষ, বন্ধু, ভাই কিংবা পরিবারের কাউকে উপহার দেওয়ার জন্য এটি হতে পারে দারুণ একটি পছন্দ। কম্বোতে রয়েছে একটি স্টাইলিশ শার্ট, একটি প্রিমিয়াম ঘড়ি, একটি মানিব্যাগ, একটি বডি স্প্রে, একটি ট্রেন্ডি সানগ্লাস, একটি ফ্যাশনেবল বেল্ট এবং একটি গিফট চিরকুট।"
},





  { featured: true, id: "punjabi-01", code: "HL-PUNJ-01", name: "সেমি-সিল্ক পাঞ্জাবি", category: "punjabi", fabric: "সেমি-সিল্ক / প্রিমিয়াম কটন", fit: "রেগুলার ফিট", care: "ড্রাই ওয়াশ প্রাধান্য দিন, হালকা আয়রন", price: 1200, oldPrice: 1500, image: "/images/punjabi1-demo.jpg", sizes: ["S", "M", "L", "XL"], desc: "উৎসব ও বিশেষ অনুষ্ঠানের জন্য এলিগেন্ট সেমি-সিল্ক পাঞ্জাবি।" },
  { featured: true, id: "punjabi-02", code: "HL-PUNJ-02", name: "কটন এমব্রয়ডারি পাঞ্জাবি", category: "punjabi", fabric: "সেমি-সিল্ক / প্রিমিয়াম কটন", fit: "রেগুলার ফিট", care: "ড্রাই ওয়াশ প্রাধান্য দিন, হালকা আয়রন", price: 1350, oldPrice: 1600, image: "/images/punjabi2-demo.jpg", sizes: ["M", "L", "XL", "XXL"], desc: "হাতের কাজের নকশাযুক্ত প্রিমিয়াম কটন পাঞ্জাবি।" },
  { id: "punjabi-03", code: "HL-PUNJ-03", name: "সলিড কালার পাঞ্জাবি", category: "punjabi", fabric: "সেমি-সিল্ক / প্রিমিয়াম কটন", fit: "রেগুলার ফিট", care: "ড্রাই ওয়াশ প্রাধান্য দিন, হালকা আয়রন", price: 1100, oldPrice: null, image: "/images/punjabi3-demo.jpg", sizes: ["S", "M", "L", "XL"], desc: "সাধারণ ব্যবহার ও নামাজের জন্য আরামদায়ক সলিড কালার পাঞ্জাবি।" },

  { featured: true, id: "jersey-01", code: "HL-JER-01", name: "ক্লাব এডিশন জার্সি", category: "jersey", fabric: "স্পোর্টস-গ্রেড পলিয়েস্টার (ঘাম শোষণক্ষম)", fit: "অ্যাথলেটিক ফিট", care: "ঠান্ডা পানিতে ধোয়া, ব্লিচ পরিহার করুন", price: 900, oldPrice: 1100, image: "/images/jersey1-demo.jpg", sizes: ["S", "M", "L", "XL"], desc: "স্পোর্টস-গ্রেড ফেব্রিকে তৈরি ক্লাব এডিশন জার্সি, ঘাম শোষণে সক্ষম।" },
  { id: "jersey-02", code: "HL-JER-02", name: "ন্যাশনাল টিম জার্সি", category: "jersey", fabric: "স্পোর্টস-গ্রেড পলিয়েস্টার (ঘাম শোষণক্ষম)", fit: "অ্যাথলেটিক ফিট", care: "ঠান্ডা পানিতে ধোয়া, ব্লিচ পরিহার করুন", price: 950, oldPrice: null, image: "/images/jersey2-demo.jpg", sizes: ["S", "M", "L", "XL", "XXL"], desc: "সাপোর্টারদের জন্য বিশেষভাবে ডিজাইন করা ন্যাশনাল টিম জার্সি।" },
];
